version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        applies-to: "version-updates"
        patterns: "*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        applies-to: "version-updates"
        patterns: "*"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
